source 'http://rubygems.org'
 
gem 'rails',                   '4.2.0'
gem 'carrierwave',             '0.10.0'
gem 'bcrypt',                  '3.1.9'
gem 'mini_magick',             '3.8.0'
gem 'will_paginate',           '3.0.7'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'bootstrap-sass',          '3.2.0.0'
gem 'sass-rails',              '5.0.2'
gem 'uglifier',                '2.5.3'
gem 'coffee-rails',            '4.1.0'
gem 'jquery-rails',            '4.0.3'
gem 'jquery-ui-rails'
gem 'jbuilder',                '2.2.3'
gem 'tzinfo-data'
gem 'table_print'
gem 'sdoc',                    '0.4.0', group: :doc
gem 'gon'
gem 'jquery-turbolinks'
gem 'pg'
