development:
  :address: 'smtp.gmail.com'
  :port: 587
  :authentication: plain
  :user_name: 'testenyx'
  :password: 'nyx_258teste'
  :domain: '@gmail'
  :enable_starttls_auto: true
production:
  :address: 'smtp.gmail.com'
  :port: 587
  :authentication: plain
  :user_name: 'testenyx'
  :password: 'nyx_258teste'
  :domain: '@gmail'
  :enable_starttls_auto: true